### ISSUE TITLE
update failure - README text mistake

### ISSUE THREAD

**Issue by ubidefeo** [xjtuecho/DS213_ECHO#1]
hi @xjtuecho 

really appreciate the work and effort :)

I have just checked out your latest update and it didn't flash correclty.
I get an error on the final part (`DS213_ECHO_v20.11.25`) and I think it's because you might ahve not pushed a new hex.
Your read me clearly states `DS213_ECHO_v20.12.25.hex` but the last checked in hex is 20.11.26

everything else goes through:
- FPGA_CFG.USE
- STMU_213_018.rdy

hope you have some new binaries to push 

thanks
ubi

**Comment by ubidefeo** [comment]
@xjtuecho 
I managed.
Sorry, didn't read the final bits of update instructions about skipping 2 and 3.
Reinstalled the original 1.27 and then changed the hex like you suggest.

Flash successful, thanks :)

**Comment by monolied** [comment]
Which one did you use? 20.11.25 or 20.11.26? (I believe the readme has a combined error of having 12 instead of 11 and not being updated when 26 was out...)
